---
# grog.package
package_list:
  - name: bash-completion
  - name: ca-certificates
  - name: curl
  - name: duf
  - name: openssh-client
  - name: openssh-server
  - name: python3-psycopg2
  - name: sudo
  - name: vim
  - name: wget