---
wol_network_interface_name: eno1

# grog.package
package_list:
  - name: bash-completion
  - name: ca-certificates
  - name: cifs-utils
  - name: curl
  - name: dnsutils
  - name: duf
  - name: fail2ban
  - name: ffmpeg
  - name: fio
  - name: git
  - name: htop  
  - name: iftop
  - name: intel-gpu-tools
  - name: inxi
  - name: iotop
  - name: jq
  - name: lm-sensors
  - name: mc
  - name: molly-guard
  - name: neofetch
  - name: net-tools
  - name: nmap
  - name: openssh-client
  - name: openssh-server
  - name: python3
  - name: progress
  - name: smartmontools
  - name: sudo
  - name: tmux
  - name: tree
  - name: vim
  - name: wget