---
# grog.package
package_list:
  - name: bash-completion
  - name: ca-certificates
  - name: curl
  - name: git
  - name: htop
  - name: openssh-clients
  - name: openssh-server
  - name: sudo
  - name: vim
  - name: wget