---
# Apparemment, il y a un problème avec le paquet intel-compute-runtime (qui fournit des bibliothèques opencl pour le GPU intel) sur la dernière version du noyau Proxmox 6.8
# Le pilote NEO ne détecte pas le GPU lors de l'utilisation du kernel 6.8.x - [Issue #710 · intel/compute-runtime (github.com)](https://github.com/intel/compute-runtime/issues/710)
# La rétrogradation temporaire vers le premier noyau antérieur au 6.8 disponible sur la machine hôte Proxmox a résolu le problème

# La commande 'proxmox-boot-tool kernel list' répertorie toutes les versions de noyaux disponibles sur la machine hôte Proxmox :
# ~# proxmox-boot-tool kernel list
# Manually selected kernels:
# None.

# Automatically selected kernels:
# 6.5.13-5-pve
# 6.8.4-2-pve
# 6.8.4-3-pve

# Pour sélectionner la version 6.5.13-5-pve pour le démarrage de façon permanente, On éxecute la commande suivante :
# ~# proxmox-boot-tool kernel pin 6.5.13-5-pve et on répond Oui/Yes à la question de rafraîchissement du boot EFI

# Après redémarrage de la machine hôte Proxmox, nous avons bien démarré sur le noyau 6.5.13-5-pve
# Vérification de la prise en charge des codecs
# ~# /usr/lib/jellyfin-ffmpeg/vainfo --display drm --device /dev/dri/renderD128
# Vérification de l'état du runtime openCL
# ~# /usr/lib/jellyfin-ffmpeg/ffmpeg -v verbose -init_hw_device vaapi=va:/dev/dri/renderD128 -init_hw_device opencl@va
# Pour voir si le transcodage fonctionne, ouvrez le shell sur la machine hôte Proxmox et installez les outils GPU Intel :
# ~# intel_gpu_top

- name: INSTALLATION DES PRÉ-REQUIS LOGICIEL POUR L'ACCÉLÉRATION MATÉRIELLE
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - intel-opencl-icd
    - intel-gpu-tools
    - intel-media-va-driver
    - ocl-icd-libopencl1
    - vainfo
    - va-driver-all
    
- name: AJUSTEMENT DES DROITS SUR /dev/dri
  shell: "{{ item}}"
  with_items:
    - "chgrp video /dev/dri"
    - "chmod 755 /dev/dri"
    - "chmod 660 /dev/dri/*"

- name: AJOUT DE L'UTILISATEUR jellyfin AUX GROUPES video ET render
  shell: "{{ item}}"
  with_items:
    - "adduser jellyfin video"
    - "adduser jellyfin render"
    - "adduser jellyfin input"

- name: TRANSCODAGE - CHANGEMENT DE L'IDENTIFIANT NUMÉRIQUE DU GROUPE render ET input POUR CORRESPONDANCE AVEC L'HÔTE proxmox
  shell: "{{ item}}"
  with_items:
    - "sed -i -e 's/^crontab:x:101:$/crontab:x:103:/' -e 's/^input:x:103:jellyfin$/input:x:101:jellyfin/' /etc/group"
    - "sed -i -e 's/^sgx:x:104:$/sgx:x:106:/' -e 's/^render:x:106:jellyfin$/render:x:104:jellyfin/' /etc/group"

- name: VÉRIFICATION DE L'EXISTANCE DU DOSSIER TEMPORAIRE transcodes SUR /dev/shm POUR LE TRANSCODAGE
  ansible.builtin.file:
    path: /dev/shm/transcodes
    state: directory
    owner: "{{ secret.users.jellyfin.uid }}"
    group: "{{ secret.users.jellyfin.gid }}"
    mode: "0777"
# https://my.jellyfin.fr/web/#/dashboard/playback/transcoding -> Emplacement du transcodeur
# Remplacer /var/lib/jellyfin/transcodes par /dev/shm/transcodes

- name: REDÉMARRAGE DU CONTENEUR LXC jellyfin
  community.general.proxmox:
    node: morpheus
    api_host: 192.168.10.5
    api_user: root@pam
    api_password: "{{ secret.proxmox.morpheus.api.password }}"
    api_token_id: "{{ secret.proxmox.morpheus.api.token_id }}"
    api_token_secret: "{{ secret.proxmox.morpheus.api.token_secret }}"
    vmid: 140
    state: "started"
    timeout: 90
  delegate_to: 192.168.10.5