---
- name: INSTALLATION DES PRÉ-REQUIS LOGICIEL
  apt:
    name:
      - apt-transport-https
      - gnupg2
      - software-properties-common
    state: present

- name: AJOUT DE LA CLÉ DE SIGNATURE jellyfin AU GESTIONNAIRE DE PAQUETS apt
  get_url:
    url: https://repo.jellyfin.org/jellyfin_team.gpg.key
    dest: /etc/apt/trusted.gpg.d/jellyfin.asc
    mode: 0644
    force: false

- name: AJOUT DU DÉPÔT jellyfin
  apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/jellyfin.asc] https://repo.jellyfin.org/debian bookworm main"
    state: present
    filename: jellyfin
    update_cache: true

- name: INSTALLATION DE jellyfin
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - jellyfin

- name: ARRÊT DU SERVICE Jellyfin
  service:
    name: jellyfin
    state: stopped
    enabled: true

- name: VÉRIFICATION DU CHANGEMENT D'UTILISATEUR DANS LE FICHIER DE CONFIGURATION DU SERVICE jellyfin
  lineinfile:
    path: /lib/systemd/system/jellyfin.service
    regexp: "^User = {{ secret.users.me.name }}"
    state: absent
  check_mode: yes
  changed_when: false
  register: change_user_used_by_jellyfin

# https://github.com/tteck/Proxmox/discussions/286
- name: CHANGEMENT DE L'UTILISATEUR UTILISÉ PAR LE SERVICE jellyfin
  lineinfile:
    dest: /lib/systemd/system/jellyfin.service
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    owner: root
    group: root
    mode: 0644
  with_items: 
    - regexp: "^User = jellyfin"
      line: "User = {{ secret.users.me.name }}"
    - regexp: "^Group = jellyfin"
      line: "Group = {{ secret.users.me.group }}"
  when: not change_user_used_by_jellyfin.found

- name: "AJUSTEMENT DES DROITS SUR LES DOSSIERS POUR L'UTILISATEUR {{ secret.users.me.name }}"
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ secret.users.me.name }}"
    group: "{{ secret.users.me.group }}"
    mode: 0644
    recurse: true
  loop:
    - /etc/default/jellyfin
    - /usr/bin/jellyfin
    - /var/lib/jellyfin/
    - /etc/jellyfin/
    - /var/log/jellyfin/
    - /var/cache/jellyfin/
    - /usr/share/jellyfin
    - /usr/share/jellyfin-ffmpeg
    - /usr/lib/jellyfin/
    - /usr/lib/jellyfin-ffmpeg/

- name: ACTIVATION ET DÉMARRAGE DU SERVICE Jellyfin
  service:
    name: jellyfin
    state: started
    enabled: true

# - name: CHANGE GROUPES
#   command: "sed -i -e 's/^ssl-cert:x:104:$/render:x:104:root,jellyfin/' -e 's/^render:x:108:root,jellyfin$/ssl-cert:x:108:/' /etc/group"