---
- name: CHARGEMENT DES VARIABLES
  include_vars: defaults/main.yml

- name: CRÉATION DU RÉPERTOIRE D'INSTALLATION/CONFIGURATION POUR LA STACK jellyfin
  become: true
  file:
    path: "/opt/{{ item }}"
    state: directory
    mode: "{{ docker.compose.directory_mask }}"
    owner: "{{ secret.users.me.name }}"
    group: "{{ secret.users.me.gid }}"
  loop:
    - docker
    - docker/jellyfin-stack
 
- name: ON S'ASSURE QU'UN FICHIER docker-compose.yml EXISTE
  remote_user: "{{ secret.users.me.name }}"
  stat:
    path: /opt/docker/jellyfin-stack/docker-compose.yml
  register: jellyfin_stack_docker_compose

- name: SUPPRESSION DE LA STACK webapps SI ELLE EXISTE
  remote_user: "{{ secret.users.me.name }}"
  shell:
    chdir: /opt/docker/jellyfin-stack
    cmd: docker compose down
  when: jellyfin_stack_docker_compose.stat.exists

- name: INSTALLATION DU FICHIER DE COMPOSITION
  template:
    src: docker-compose.yml.j2
    dest: /opt/docker/jellyfin-stack/docker-compose.yml
    mode: "{{ docker.compose.file_mask }}"
    owner: "{{ secret.users.me.name }}"
    group: "{{ secret.users.me.gid }}"
    validate: docker compose -f %s config

- name: INSTALLATION DU FICHIER DES VARIABLES D'ENVIRONNEMENT DOCKER
  template:
    src: env.j2
    dest: /opt/docker/jellyfin-stack/.env
    mode: "{{ docker.compose.file_mask }}"
    owner: "{{ secret.users.me.name }}"
    group: "{{ secret.users.me.gid }}"

- name: INSTALLATION/CONFIGURATION DU CONTENEUR jellyfin
  include_tasks: docker/containers/jellyfin.yml

- name: INSTALLATION/CONFIGURATION DU CONTENEUR jellyfin
  include_tasks: docker/containers/tinymediamanager.yml

- name: DÉMARRAGE DE LA STACK jellyfin
  remote_user: "{{ secret.users.me.name }}"
  shell:
    chdir: /opt/docker/jellyfin-stack
    cmd: docker compose up -d