---
clone:
  git:
    image: woodpeckerci/plugin-git
    commands:
      - mkdir -p /home/allfab && cd /home/allfab
      - git clone https://github.com/allfab/infrastructure
      - git remote add forgejo https://forgejo.allfabox.fr/allfab/infrastructure.git
      - git push forgejo main
    # environment:
    #   VAULT_FORGEJO_INFRA_GIT_REPO:
    #     from_secret: VAULT_FORGEJO_INFRA_GIT_REPO

steps:
    - name: ntfy
      image: codeberg.org/l-x/woodpecker-ntfy
      when:
        - event: push
      settings:
          url:
            from_secret: VAULT_NTFY_URL
          title: Commit by ${CI_COMMIT_AUTHOR} on ${CI_COMMIT_BRANCH}
          priority: high
          # actions: "view, Open portal, https://home.nest.com/, clear=true; http, Turn down, https://api.nest.com/, body='{\"temperature\": 65}'"
          click:
            from_secret: VAULT_FORGEJO_URL
          icon: https://woodpecker-ci.org/img/logo.svg
          tags: robot,${CI_REPO_NAME}
          message: ${CI_COMMIT_MESSAGE}