---
- hosts: all
  tags: timezone
  vars_files:
    - vars/vault.yml
  tasks:
    - name: DÉFINITION DU FUSEAU HORAIRE
      community.general.timezone:
        name: "{{ timezone }}"
  
- hosts: pve
  tags: config
  vars_files:
    - vars/vault.yml
  roles:
    - role: pve/community-repo
      tags: pve-community-repo
    - role: pve/fake-subscription
      tags: pve-fake-subscription
    - role: config/users
      tags: pve-users
    # - role: config/security
    #   tags: pve-ssh
    - role: pve/wake-on-lan
      tags: pve-wol
    - role: config/bash-aliases
      tags: pve-alias
    - role: grog.package
      tags: pve-package
    - role: install/zellij
      tags: install-zellij
    - role: install/motd
      tags: pve-motd
    # - role: install/fail2ban
    #   tags: pve-fail2ban

- hosts: morpheus
  tags: config
  vars_files:
    - vars/vault.yml
  roles:
    - role: pve/community-repo
      tags: pve-community-repo
    - role: pve/fake-subscription
      tags: pve-fake-subscription
    - role: config/users
      tags: pve-users
    # - role: config/security
    #   tags: pve-ssh
    - role: pve/wake-on-lan
      tags: pve-wol
    - role: config/bash-aliases
      tags: pve-alias
    - role: grog.package
      tags: pve-package
    - role: install/zellij
      tags: install-zellij
    - role: install/motd
      tags: pve-motd
    # - role: install/fail2ban
    #   tags: pve-fail2ban

- hosts: neo
  tags: config
  vars_files:
    - vars/vault.yml
  roles:
    - role: pve/community-repo
      tags: pve-community-repo
    - role: pve/fake-subscription
      tags: pve-fake-subscription
    - role: config/users
      tags: pve-users
    # - role: config/security
    #   tags: pve-ssh
    - role: pve/wake-on-lan
      tags: pve-wol
    - role: config/bash-aliases
      tags: pve-alias
    - role: grog.package
      tags: pve-package
    - role: install/zellij
      tags: install-zellij
    - role: install/motd
      tags: pve-motd
    # - role: install/fail2ban
    #   tags: pve-fail2ban

- hosts: morpheus
  tags: setup
  vars_files:
    - vars/vault.yml
  roles:
    - role: morpheus
      tags: morpheus-setup
    - role: config/bash-aliases
      tags: morpheus-alias
    - role: grog.package
      tags: morpheus-package
    - role: install/mergerfs
      tags: morpheus-mergerfs
    - role: install/snapraid
      tags: morpheus-snapraid

- hosts: morpheus
  tags: lnxlink
  vars_files:
    - vars/vault.yml
  roles:
    - role: install/lnxlink
      tags: lnxlink-setup

- hosts: neo
  tags: lnxlink
  vars_files:
    - vars/vault.yml
  roles:
    - role: install/lnxlink
      tags: lnxlink-setup

- hosts: frontend
  tags: setup
  vars_files:
    - vars/vault.yml
  pre_tasks:
    - name: MISE À JOUR SYSTÈME
      become: true
      apt:
        update_cache: true
        upgrade: true
        cache_valid_time: 14400
  roles:
    - role: grog.package
      become: true
    - config/users
    - role: config/bash-aliases
      become: true
    - install/motd
    - role: geerlingguy.docker
      become: true
    - role: frontend
      become: true

- hosts: elephant
  tags: setup
  vars_files:
    - vars/vault.yml
  pre_tasks:
    - name: MISE À JOUR SYSTÈME
      become: true
      apt:
        update_cache: true
        upgrade: true
        cache_valid_time: 14400
  roles:
    - role: grog.package
      become: true
    - config/users
    - role: config/bash-aliases
      become: true
    - install/motd
    - install/postgresql

- hosts: smarthome
  tags: setup
  vars_files:
    - vars/vault.yml
  pre_tasks:
    - name: MISE À JOUR SYSTÈME
      become: true
      apt:
        update_cache: true
        upgrade: true
        cache_valid_time: 14400
  roles:
    - role: grog.package
      become: true
    - config/users
    - role: config/bash-aliases
      become: true
    - install/motd
    - role: geerlingguy.docker
      become: true
    - role: smarthome
      become: true

- hosts: jellyfin
  tags: setup
  vars_files:
    - vars/vault.yml
  pre_tasks:
    - name: MISE À JOUR SYSTÈME
      become: true
      apt:
        update_cache: true
        upgrade: true
        cache_valid_time: 14400
  roles:
    - role: grog.package
      become: true
    - config/users
    - role: config/bash-aliases
      become: true
    - install/motd
    - role: jellyfin
      become: true

- hosts: mediaserver
  tags: setup
  vars_files:
    - vars/vault.yml
  pre_tasks:
    - name: MISE À JOUR SYSTÈME
      become: true
      apt:
        update_cache: true
        upgrade: true
        cache_valid_time: 14400
  roles:
    - role: grog.package
      become: true
    - config/users
    - role: config/bash-aliases
      become: true
    - install/motd
    - role: geerlingguy.docker
      become: true
    - role: mediaserver
      become: true
  
- hosts: nextcloud
  tags: setup
  vars_files:
    - vars/vault.yml
  pre_tasks:
    - name: MISE À JOUR SYSTÈME
      become: true
      apt:
        update_cache: true
        upgrade: true
        cache_valid_time: 14400
  roles:
    - role: grog.package
      become: true
    - config/users
    - role: config/bash-aliases
      become: true
    - install/motd
    - role: geerlingguy.docker
      become: true
    - role: nextcloud
      become: true

- hosts: immich
  tags: setup
  vars_files:
    - vars/vault.yml
  pre_tasks:
    - name: MISE À JOUR SYSTÈME
      become: true
      apt:
        update_cache: true
        upgrade: true
        cache_valid_time: 14400
  roles:
    - role: grog.package
      become: true
    - config/users
    - role: config/bash-aliases
      become: true
    - install/motd
    - role: geerlingguy.docker
      become: true
    - role: immich
      become: true

- hosts: webapps
  tags: setup
  vars_files:
    - vars/vault.yml
  pre_tasks:
    - name: MISE À JOUR SYSTÈME
      become: true
      apt:
        update_cache: true
        upgrade: true
        cache_valid_time: 14400
  roles:
    - role: grog.package
      become: true
    - config/users
    - role: config/bash-aliases
      become: true
    - install/motd
    - role: geerlingguy.docker
      become: true
    - role: webapps
      become: true

- hosts: monitoring
  tags: setup
  vars_files:
    - vars/vault.yml
  pre_tasks:
    - name: MISE À JOUR SYSTÈME
      become: true
      apt:
        update_cache: true
        upgrade: true
        cache_valid_time: 14400
  roles:
    - role: grog.package
      become: true
    - config/users
    - role: config/bash-aliases
      become: true
    - install/motd
    - role: geerlingguy.docker
      become: true
    - role: monitoring
      become: true

- hosts: communication
  tags: setup
  vars_files:
    - vars/vault.yml
  pre_tasks:
    - name: MISE À JOUR SYSTÈME
      become: true
      apt:
        update_cache: true
        upgrade: true
        cache_valid_time: 14400
  roles:
    - role: grog.package
      become: true
    - config/users
    - role: config/bash-aliases
      become: true
    - install/motd
    - role: geerlingguy.docker
      become: true
    - role: communication
      become: true

- hosts: hetzner
  tags: setup
  vars_files:
    - vars/vault.yml
  pre_tasks:
    - name: MISE À JOUR SYSTÈME
      become: true
      apt:
        update_cache: true
        upgrade: true
        cache_valid_time: 14400
  roles:
    - role: config/bash-aliases
      become: true
    - install/motd
    - role: vps/frontend
      become: true

# - hosts: morpheus
#   tags: destroy-infra
#   vars_files:
#     - vars/vault.yml
#   vars_prompt:
#     - name: morpheus_destroy_infra
#       prompt: Voulez-vous supprimer l'infrasctucture mise en place (oui, yes) ?
#       private: false
#   roles:
#     - role: infra/destroy
#       tags: morpheus-destroy-infra
#       when: morpheus_destroy_infra == 'yes' or morpheus_destroy_infra == 'oui'