---
- name: CHARGEMENT DES VARIABLES
  include_vars: defaults/main.yml

- name: CRÉATION DU RÉPERTOIRE D'INSTALLATION/CONFIGURATION POUR LA STACK sysadmin
  become: true
  file:
    path: "/opt/{{ item }}"
    state: directory
    mode: "{{ docker.compose.directory_mask }}"
    owner: "{{ secret.users.me.name }}"
    group: "{{ secret.users.me.gid }}"
  loop:
    - docker
    - docker/sysadmin-stack
 
- name: ON S'ASSURE QU'UN FICHIER docker-compose.yml EXISTE
  remote_user: "{{ secret.users.me.name }}"
  stat:
    path: /opt/docker/sysadmin-stack/docker-compose.yml
  register: sysadmin_stack_docker_compose

- name: SUPPRESSION DE LA STACK sysadmin SI ELLE EXISTE
  remote_user: "{{ secret.users.me.name }}"
  shell:
    chdir: /opt/docker/sysadmin-stack
    cmd: docker compose down
  when: sysadmin_stack_docker_compose.stat.exists

- name: INSTALLATION DU FICHIER DE COMPOSITION
  template:
    src: docker-compose.yml.j2
    dest: /opt/docker/sysadmin-stack/docker-compose.yml
    mode: "{{ docker.compose.file_mask }}"
    owner: "{{ secret.users.me.name }}"
    group: "{{ secret.users.me.gid }}"
    validate: docker compose -f %s config

- name: INSTALLATION DU FICHIER DES VARIABLES D'ENVIRONNEMENT DOCKER
  template:
    src: env.j2
    dest: /opt/docker/sysadmin-stack/.env
    mode: "{{ docker.compose.file_mask }}"
    owner: "{{ secret.users.me.name }}"
    group: "{{ secret.users.me.gid }}"

- name: INSTALLATION/CONFIGURATION DU CONTENEUR healthchecks
  include_tasks: docker/containers/healthchecks.yml

- name: INSTALLATION/CONFIGURATION DU CONTENEUR uptime-kuma
  include_tasks: docker/containers/uptime-kuma.yml

- name: INSTALLATION/CONFIGURATION DU CONTENEUR nexterm
  include_tasks: docker/containers/nexterm.yml

- name: DÉMARRAGE DE LA STACK sysadmin
  remote_user: "{{ secret.users.me.name }}"
  shell:
    chdir: /opt/docker/sysadmin-stack
    cmd: docker compose up -d

- name: CHANGEMENT DES DROITS UTILISATEUR SUR L'ENSEMBLE DU DOSSIER /opt/docker/sysadmin-stack
  file:
    dest: /opt/docker/sysadmin-stack
    owner: "{{ secret.users.me.uid }}"
    group: "{{ secret.users.me.gid }}"
    mode: "0777"
    recurse: true