---
- name: VÉRIFICATION DE L'EXISTENCE DE L'INSTALLATION DU PAQUET
  shell: "dpkg-query -W 'pve-fake-subscription'"
  ignore_errors: true
  register: is_installed
  changed_when: "is_installed.rc != 0"

- name: INSTALLATION DU PAQUET ?
  set_fact:
    force_install: "{{ fake_subscription_force_install == true or is_installed.failed == true }}"

- name: OBTENTION DE LA DERNIÈRE VERSION
  uri:
    url: https://api.github.com/repos/Jamesits/pve-fake-subscription/releases/latest
    url_username: "{{ secret.github.api.user | default (omit) }}"
    url_password: "{{ secret.github.api.token | default (omit) }}"
    return_content: true
    force_basic_auth: "{{ secret.github.api.auth | default (omit) }}"
  register: release_latest
  when: fake_subscription_version is undefined and force_install == True

- name: DÉFINITION DE LA VERSION SI CE N'EST PAS LE CAS
  set_fact: 
    fake_subscription_version: "{{ release_latest.json.tag_name }}"
  when: fake_subscription_version is undefined and force_install == True

- name: TÉLÉCHARGEMENT DE LA VERSION SOUHAITÉE
  get_url:
    url: https://github.com/Jamesits/pve-fake-subscription/releases/download/{{ fake_subscription_version }}/pve-fake-subscription_{{ fake_subscription_version | regex_replace('v') }}+git-1_all.deb
    dest: /tmp
  when: force_install == True

- name: DÉFINITION DU NOM DU FICHIER
  set_fact:
    file_name: "pve-fake-subscription_{{ fake_subscription_version | regex_replace('v') }}+git-1_all.deb"
  when: force_install == True

- name: INSTALLATION DU FICHIER .deb
  apt:
    deb: /tmp/{{ file_name }}
    state: present
  when: force_install == True
