---
- name: CRÉATION DES CONTENEUR LXC
  proxmox:
    proxmox_default_behavior: no_defaults
    node: morpheus
    api_host: 192.168.10.5
    api_user: root@pam
    api_password: "{{ secret.proxmox.morpheus.api.password }}"
    api_token_id: "{{ secret.proxmox.morpheus.api.token_id }}"
    api_token_secret: "{{ secret.proxmox.morpheus.api.token_secret }}"
    vmid: "{{ item.vmid }}"
    cores: "{{ item.cores }}"
    cpus: "1"
    cpuunits: "1000"
    description: |
      {{ item.description }}
    disk: "{{ item.disk }}"
    features:
      - fuse={{ item.fuse | default ('0') }}
      - keyctl={{ item.keyctl | default ('0') }}
      - nesting={{ item.nesting | default ('1') }}
    hostname: "{{ item.name }}"
    memory: "{{ item.memory }}"
    nameserver: "{{ item.nameserver | default ('192.168.0.253') }}"
    netif: "{'net0':'name=eth0,ip={{ item.ip }}/24,gw={{ item.gw }},bridge={{ item.bridge | default ('vmbr0') }},firewall={{ item.firewall | default ('1') }}'}"
    onboot: "{{ item.onboot | default ('true') }}"
    ostemplate: "{{ item.ostemplate | default ('iso:vztmpl/debian-12-standard_12.2-1_amd64.tar.zst') }}"
    password: "{{ secret.users.lxc.ssh.password }}"
    pubkey: "{{ secret.users.me.ssh.pubkey }}"
    storage: local-zfs
    swap: "{{ item.swap | default ('512') }}"
    tags: "{{ item.tags }}"
    timezone: "{{ timezone }}"
    unprivileged: "{{ item.unprivileged | default ('true') }}"
    state: present
  loop: "{{ lxc_to_deploy }}"

- name: DÉFINITION DE L'ORDRE DE DÉMARRAGE DES CONTENEURS LXC
  shell: pct set {{ item.lxc }} --startup order={{ item.order }}
  loop:
    - {"lxc":"110", "order":"1"}
    - {"lxc":"120", "order":"2"}
    - {"lxc":"130", "order":"3"}
    - {"lxc":"140", "order":"4"}
    - {"lxc":"141", "order":"5"}
    - {"lxc":"142", "order":"6"}
    - {"lxc":"150", "order":"7"}
    - {"lxc":"160", "order":"8"}

- name: "VÉRIFICATION DE LA PRÉSENCE DE LA CONFIGURATION POUR LA FONCTION TUN/TAP frontend"
  lineinfile:
    path: /etc/pve/lxc/110.conf
    regexp: "^lxc.cgroup2.devices.allow: c 10:200 rwm"
    state: absent
  check_mode: yes
  changed_when: false
  register: tun_tap_exists

- name: "AJOUT DE LA CONFIGURATION POUR LA FONCTION TUN/TAP - CONTENEUR NON PRIVILÉGIÉ"
  lineinfile:
    path: /etc/pve/lxc/110.conf
    insertafter: EOF
    line: |
      lxc.cgroup2.devices.allow: c 10:200 rwm
      lxc.mount.entry: /dev/net/tun dev/net/tun none bind,create=file
    unsafe_writes: yes
  when: not tun_tap_exists.found

- name: AJOUT DES POINTS DE MONTAGE LXC SUR LES CONTENEURS LXC
  command: "{{ item }}"
  with_items:
    - "pct set 120 -mp1 /home/postgres,mp=/home/postgres"
    - "pct set 140 -mp1 /mnt/storage/videos,mp=/mnt/videos"
    - "pct set 141 -mp1 /mnt/storage/musics,mp=/mnt/musics"
    - "pct set 141 -mp2 /mnt/storage/books,mp=/mnt/books"
    - "pct set 150 -mp1 /mnt/storage,mp=/mnt/storage"
    - "pct set 150 -mp2 /mnt/freebox,mp=/mnt/freebox"

- name: VÉRIFICATION DE LA PRÉSENCE DU RELAIS iGPU DANS LE FICHIER DE CONFIGURATION Jellyfin /etc/pve/lxc/140.conf
  lineinfile:
    path: /etc/pve/lxc/140.conf
    regexp: "^lxc.cgroup2.devices.allow: c 226:0 rwm"
    state: absent
  check_mode: yes
  changed_when: false
  register: igpu_exists

- name: AJOUT DU RELAIS iGPU DANS LE FICHIER DE CONFIGURATION Jellyfin /etc/pve/lxc/140.conf
  lineinfile:
    dest: /etc/pve/lxc/140.conf
    insertafter: EOF
    line: |
      lxc.cgroup2.devices.allow: c 226:0 rwm
      lxc.cgroup2.devices.allow: c 226:128 rwm
      lxc.mount.entry: /dev/dri/card0 dev/dri/card0 none bind,optional,create=file
      lxc.mount.entry: /dev/dri/renderD128 dev/dri/renderD128 none bind,optional,create=file
    unsafe_writes: yes
  when: not igpu_exists.found

- name: ACTIVATION DU FIRMWARE Intel GUC/HUC POUR Jellyfin
  template:
    src: jellyfin/i915.conf.j2
    dest: /etc/modprobe.d/i915.conf
    owner: root
    group: root
    mode: 0600
  when: intel_jasper_lake_or_elkhart_lake_processor == true

- name: DÉMARRAGE DES CONTENEURS LXC
  community.general.proxmox:
    node: morpheus
    api_host: 192.168.10.5
    api_user: root@pam
    api_password: "{{ secret.proxmox.morpheus.api.password }}"
    api_token_id: "{{ secret.proxmox.morpheus.api.token_id }}"
    api_token_secret: "{{ secret.proxmox.morpheus.api.token_secret }}"
    vmid: "{{ item.lxc }}"
    state: "started"
    timeout: 90
  loop:
    - {"lxc":"110"}
    - {"lxc":"120"}
    - {"lxc":"130"}
    - {"lxc":"140"}
    - {"lxc":"141"}
    - {"lxc":"142"}
    - {"lxc":"150"}
    - {"lxc":"160"}