---
- name: CHARGEMENT DES VARIABLES
  include_vars: defaults/main.yml

- name: CRÉATION DU RÉPERTOIRE D'INSTALLATION/CONFIGURATION POUR L'ENSEMBLE DES STACKS
  become: true
  file:
    path: "/opt/{{ item }}"
    state: directory
    mode: "{{ docker.compose.directory_mask }}"
    owner: "{{ secret.users.me.name }}"
    group: "{{ secret.users.me.gid }}"
  loop:
    - docker/webgis-stack

- name: ON S'ASSURE QU'UN FICHIER docker-compose.yml EXISTE
  stat:
    path: /opt/docker/webgis-stack/docker-compose.yml
  register: webgis_stack_docker_compose

- name: SUPPRESSION DE LA STACK webgis SI ELLE EXISTE
  shell:
    chdir: /opt/docker/webgis-stack
    cmd: docker compose down
  when: webgis_stack_docker_compose.stat.exists

- name: INSTALLATION DU FICHIER DE COMPOSITION
  template:
    src: webgis/docker-compose.yml.j2
    dest: /opt/docker/webgis-stack/docker-compose.yml
    mode: "{{ docker.compose.file_mask }}"
    owner: "{{ secret.users.me.name }}"
    group: "{{ secret.users.me.gid }}"
    validate: docker compose -f %s config

- name: INSTALLATION DU FICHIER DES VARIABLES D'ENVIRONNEMENT DOCKER
  become: true
  template:
    src: webgis/env.j2
    dest: /opt/docker/webgis-stack/.env
    mode: "{{ docker.compose.file_mask }}"
    owner: "{{ secret.users.me.name }}"
    group: "{{ secret.users.me.gid }}"

- name: DÉMARRAGE DE LA STACK webgis
  shell:
    chdir: /opt/docker/webgis-stack
    cmd: docker compose up -d

- name: CHANGEMENT DES DROITS UTILISATEUR SUR L'ENSEMBLE DU DOSSIER /opt/docker/webgis-stack
  become: true
  file:
    dest: /opt/docker/webgis-stack
    owner: "{{ secret.users.me.uid }}"
    group: "{{ secret.users.me.gid }}"
    mode: "0755"
    recurse: true