---
- name: CHARGEMENT DES VARIABLES
  include_vars: defaults/main.yml
 
- name: ON S'ASSURE QU'UN FICHIER docker-compose.yml EXISTE
  remote_user: "{{ secret.users.me.name }}"
  stat:
    path: /opt/docker/webapps-stack/docker-compose.yml
  register: webapps_stack_docker_compose

- name: SUPPRESSION DE LA STACK webapps SI ELLE EXISTE
  remote_user: "{{ secret.users.me.name }}"
  shell:
    chdir: /opt/docker/webapps-stack
    cmd: docker compose down
  when: webapps_stack_docker_compose.stat.exists

- name: INSTALLATION DU FICHIER DE COMPOSITION
  template:
    src: docker-compose.yml.j2
    dest: /opt/docker/webapps-stack/docker-compose.yml
    mode: "{{ docker.compose.file_mask }}"
    owner: "{{ secret.users.me.name }}"
    group: "{{ secret.users.me.gid }}"
    validate: docker compose -f %s config

- name: INSTALLATION DU FICHIER DES VARIABLES D'ENVIRONNEMENT DOCKER
  template:
    src: env.j2
    dest: /opt/docker/webapps-stack/.env
    mode: "{{ docker.compose.file_mask }}"
    owner: "{{ secret.users.me.name }}"
    group: "{{ secret.users.me.gid }}"

- name: INSTALLATION/CONFIGURATION DU CONTENEUR homer
  include_tasks: includes/docker/homer.yml

- name: INSTALLATION/CONFIGURATION DU CONTENEUR vaultwarden
  include_tasks: includes/docker/vaultwarden.yml

- name: DÉMARRAGE DE LA STACK webapps
  remote_user: "{{ secret.users.me.name }}"
  shell:
    chdir: /opt/docker/webapps-stack
    cmd: docker compose up -d

- name: CHANGEMENT DES DROITS UTILISATEUR SUR L'ENSEMBLE DU DOSSIER /opt/docker/webapps-stack
  file:
    dest: /opt/docker/webapps-stack
    owner: "{{ secret.users.me.uid }}"
    group: "{{ secret.users.me.gid }}"
    mode: "0775"
    recurse: true