---
- name: CHARGEMENT DES VARIABLES
  include_vars: defaults/main.yml

- name: CRÉATION DU RÉPERTOIRE D'INSTALLATION/CONFIGURATION POUR L'ENSEMBLE DES STACKS
  become: true
  file:
    path: "/opt/{{ item }}"
    state: directory
    mode: "{{ docker.compose.directory_mask }}"
    owner: "{{ secret.users.me.name }}"
    group: "{{ secret.users.me.gid }}"
  loop:
    - docker

- name: INSTALLATION/CONFIGURATION DE LA STACK webgis
  include_tasks: docker/stacks/webgis.yml

# - name: INSTALLATION/CONFIGURATION DE LA STACK qfieldcloud
#   include_tasks: docker/stacks/qfieldcloud.yml