---
- name: CHARGEMENT DES VARIABLES
  include_vars: defaults/main.yml

- name: CRÉATION DU RÉPERTOIRE D'INSTALLATION/CONFIGURATION POUR L'ENSEMBLE DES STACKS
  become: true
  file:
    path: "/opt/{{ item }}"
    state: directory
    mode: "{{ docker.compose.directory_mask }}"
    owner: "{{ secret.users.me.name }}"
    group: "{{ secret.users.me.gid }}"
  loop:
    - docker

- name: INSTALLATION/CONFIGURATION DE LA STACK qfieldcloud
  include_tasks: docker/stacks/qfieldcloud.yml

# - name: ON S'ASSURE QU'UN FICHIER docker-compose.yml EXISTE
#   stat:
#     path: /opt/docker/webgis-stack/docker-compose.yml
#   register: webgis_stack_docker_compose

# - name: SUPPRESSION DE LA STACK webgis SI ELLE EXISTE
#   shell:
#     chdir: /opt/docker/webgis-stack
#     cmd: docker compose down
#   when: webgis_stack_docker_compose.stat.exists

# - name: INSTALLATION DU FICHIER DE COMPOSITION
#   template:
#     src: docker-compose.yml.j2
#     dest: /opt/docker/webgis-stack/docker-compose.yml
#     mode: "{{ docker.compose.file_mask }}"
#     owner: "{{ secret.users.me.name }}"
#     group: "{{ secret.users.me.gid }}"
#     validate: docker compose -f %s config

# - name: INSTALLATION DU FICHIER DES VARIABLES D'ENVIRONNEMENT DOCKER
#   become: true
#   template:
#     src: env.j2
#     dest: /opt/docker/webgis-stack/.env
#     mode: "{{ docker.compose.file_mask }}"
#     owner: "{{ secret.users.me.name }}"
#     group: "{{ secret.users.me.gid }}"

# - name: INSTALLATION/CONFIGURATION DU CONTENEUR filebrowser
#   include_tasks: docker/containers/filebrowser.yml

# - name: DÉMARRAGE DE LA STACK webgis
#   shell:
#     chdir: /opt/docker/webgis-stack
#     cmd: docker compose up -d

# - name: CHANGEMENT DES DROITS UTILISATEUR SUR L'ENSEMBLE DU DOSSIER /opt/docker/webgis-stack
#   become: true
#   file:
#     dest: /opt/docker/webgis-stack
#     owner: "{{ secret.users.me.uid }}"
#     group: "{{ secret.users.me.gid }}"
#     mode: "0755"
#     recurse: true