---
- name: CHARGEMENT DES VARIABLES PAR DÉFAUT
  include_vars: defaults/main.yml

- name: PRÉREQUIS - DÉPENDANCES
  become: true
  apt:
    name:
      - "python3-cryptography"
    state: "present"

- name: ONLYOFFICE - CRÉATION DU RÉPERTOIRE D'INSTALLATION/CONFIGURATION
  file:
    path: /opt/docker/nextcloud-stack/onlyoffice
    state: directory
    mode: "{{ docker.compose.directory_mask }}"
    owner: "{{ secret.users.me.uid }}"
    group: "{{ secret.users.me.gid }}"

- name: ONLYOFFICE - CRÉATION DU RÉPERTOIRE D'INSTALLATION/CONFIGURATION
  file:
    path: "/opt/docker/nextcloud-stack/onlyoffice/{{ item }}"
    state: directory
    mode: "{{ docker.compose.directory_mask }}"
    owner: "{{ secret.users.me.uid }}"
    group: "{{ secret.users.me.gid }}"
    recurse: true
  loop:
    - data
    - lib
    - logs

# https://helpcenter.onlyoffice.com/installation/groups-https-docker.aspx
- name: ONLYOFFICE - GÉNÉRATION DES CERTIFICATS AUTO-SIGNÉS - CRÉATION DU RÉPERTOIRE certs
  file:
    path: /opt/docker/nextcloud-stack/onlyoffice/data/certs
    state: directory
    mode: "{{ docker.compose.directory_mask }}"
    owner: "{{ secret.users.me.uid }}"
    group: "{{ secret.users.me.gid }}"

- name: ONLYOFFICE - GÉNÉRATION DES CERTIFICATS AUTO-SIGNÉS - CRÉATION DE LA CLÉ PRIVÉE DU SERVEUR
  community.crypto.openssl_privatekey:
    path: /opt/docker/nextcloud-stack/onlyoffice/data/certs/onlyoffice.key
    type: RSA
    size: 2048

- name: ONLYOFFICE - GÉNÉRATION DES CERTIFICATS AUTO-SIGNÉS - CRÉATION DE LA DEMANDE DE SIGNATURE DE CERTIFICAT (CSR)
  community.crypto.openssl_csr:
    path: /opt/docker/nextcloud-stack/onlyoffice/data/certs/onlyoffice.csr
    privatekey_path: /opt/docker/nextcloud-stack/onlyoffice/data/certs/onlyoffice.key
    common_name: allfabox.home

- name: ONLYOFFICE - GÉNÉRATION DES CERTIFICATS AUTO-SIGNÉS - SIGNATURE DU CERTIFICAT À L'AIDE DE LA CLÉ PRIVÉE ET DU CSR
  community.crypto.x509_certificate:
    path: /opt/docker/nextcloud-stack/onlyoffice/data/certs/onlyoffice.crt
    privatekey_path: /opt/docker/nextcloud-stack/onlyoffice/data/certs/onlyoffice.key
    csr_path: /opt/docker/nextcloud-stack/onlyoffice/data/certs/onlyoffice.csr
    provider: selfsigned

- name: ONLYOFFICE - GÉNÉRATION DES CERTIFICATS AUTO-SIGNÉS - RENFORCEMENT DE LA SÉCURITÉ DU SERVEUR
  community.crypto.openssl_dhparam:
    path: /opt/docker/nextcloud-stack/onlyoffice/data/certs/dhparams.pem
    size: 2048

- name: ONLYOFFICE - GÉNÉRATION DES CERTIFICATS AUTO-SIGNÉS - SUPPRESSION DE LA DEMANDE DE SIGNATURE DE CERTIFICAT (CSR)
  ansible.builtin.file:
    path: /opt/docker/nextcloud-stack/onlyoffice/data/certs/onlyoffice.csr
    state: absent

- name: ONLYOFFICE - GÉNÉRATION DES CERTIFICATS AUTO-SIGNÉS - PERMISSIONS 0400
  ansible.builtin.file:
    path: /opt/docker/nextcloud-stack/onlyoffice/data/certs/onlyoffice.key
    mode: "0400"
    owner: "{{ secret.users.me.uid }}"
    group: "{{ secret.users.me.gid }}"

# # https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/821
# - name: ONLYOFFICE - https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/821
#   ansible.builtin.command: docker exec onlyoffice sudo sed 's/\"rejectUnauthorized": true, "rejectUnauthorized": false,' -i /etc/onlyoffice/documentserver/default.json

# sed "s\/'rejectUnauthorized':\true\/PermitRootLogin yes\/"
# sed "s/\('name':\)/\1\"hello\"\,/g" /path/to/file.json
# # "rejectUnauthorized": true
# # docker exec onlyoffice sudo sed 's,autostart=false,autostart=true,' -i /etc/supervisor/conf.d/ds-nextcloud.conf
# # docker exec caa6bfabc2ef sudo supervisorctl start ds:nextcloud
# # sudo service supervisor status
# # sudo docker exec caa6bfabc2ef sudo supervisorctl start ds:nextcloud
# # docker exec onlyoffice sudo supervisorctl start ds:nextcloud

# sed 's/"spark.driver.memory" : "[0-9]gb"/"spark.driver.memory" : "1gb"/;s/"spark.executor.memory" : "[0-9]gb"/"spark.executor.memory" : "1gb"/;s/"spark.cores.max": "[0-9]"/"spark.cores.max" :"1"/;s/"period" : "[0-9]*"/"period" : "15"/'   Input_file

