---
- name: SUPPRESSION DU DÉPÔT 'pve-enterprise'
  file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent

- name: SUPPRESSION DU DÉPÔT 'ceph'
  file:
    path: /etc/apt/sources.list.d/ceph.list
    state: absent

- name: AJOUT DU DÉPÔT COMMUNAUTAIRE 'pve-no-subscription'
  apt_repository:
    repo: "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription"
    filename: pve-no-subscription
    state: present