---
# tasks file for roles/postgresql/includes/install.yml
- name: AJOUT DE LA CLÉ DE SIGNATURE PostgreSQL AU GESTIONNAIRE DE PAQUETS 'APT'
  get_url:
    url: "{{ postgresql.apt.key.url }}"
    dest: "{{ postgresql.apt.key.dest }}"
    mode: 0644
    force: false

- name: AJOUT DU DÉPÔT PostgreSQL DE LA COMMUNAUTÉ
  apt_repository:
    repo: "deb [signed-by={{ postgresql.apt.key.dest }}] {{ postgresql.apt.repo_url }} {{ ansible_distribution_release }}-pgdg main"
    state: present
    filename: pgdg.list
    update_cache: true

- name: CONFIGURATION DES PARAMÈTRES RÉGIONAUX
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items: "{{ postgresql.locales }}"
  register: locale_gen_result

- name: INSTALLATION DES LIBRAIRIES PYTHON REQUISES
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ postgresql.python.library}}"

- name: INSTALLATION DES PAQUETS PostgreSQL
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ postgresql.packages }}"

- name: "REDÉMARRAGE DE PostgreSQL APRÈS LA GÉNÉRATION DE NOUVEAUX PARAMÈTRES RÉGIONAUX {{ postgresql.locales }}"
  service:
    name: postgresql
    state: restarted
  when: locale_gen_result.changed