---
# tasks file for roles/postgresql/includes/user.yml
- name: CRÉATION DE L'UTILISATEUR postgres
  user:
    name: "{{ postgresql.user.name }}"    
    uid: "{{ postgresql.user.uid }}"
    group: "{{ postgresql.user.gid }}"
    create_home: false
    home: "{{ postgresql.directories.home }}"
    shell: /bin/bash
    system: true
    comment: "{{ postgresql.user.comment }}"

- name: DÉFINITION DES VARIABLES D'ENVIRONNEMENT PostgreSQL
  template:
    src: postgres.sh.j2
    dest: /etc/profile.d/postgres.sh
    mode: 0644
