---
- name: CHARGEMENT DES VARIABLES
  include_vars: defaults/main.yml
 
- name: ON S'ASSURE QU'UN FICHIER docker-compose.yml EXISTE
  stat:
    path: /opt/docker/mediaserver-stack/docker-compose.yml
  register: mediaserver_stack_docker_compose

- name: SUPPRESSION DE LA STACK mediaserver SI ELLE EXISTE
  shell:
    chdir: /opt/docker/mediaserver-stack
    cmd: docker compose down
  when: mediaserver_stack_docker_compose.stat.exists

- name: INSTALLATION DU FICHIER DE COMPOSITION
  template:
    src: docker-compose.yml.j2
    dest: /opt/docker/mediaserver-stack/docker-compose.yml
    mode: "{{ docker.compose.file_mask }}"
    owner: "{{ secret.users.me.name }}"
    group: "{{ secret.users.me.gid }}"
    validate: docker compose -f %s config

- name: INSTALLATION DU FICHIER DES VARIABLES D'ENVIRONNEMENT DOCKER
  template:
    src: env.j2
    dest: /opt/docker/mediaserver-stack/.env
    mode: "{{ docker.compose.file_mask }}"
    owner: "{{ secret.users.me.name }}"
    group: "{{ secret.users.me.gid }}"

- name: INSTALLATION/CONFIGURATION DU CONTENEUR navidrome
  include_tasks: includes/docker/navidrome.yml

- name: INSTALLATION/CONFIGURATION DU CONTENEUR calibre-web
  include_tasks: includes/docker/calibre-web.yml

- name: DÉMARRAGE DE LA STACK mediaserver
  shell:
    chdir: /opt/docker/mediaserver-stack
    cmd: docker compose up -d

- name: CHANGEMENT DES DROITS UTILISATEUR SUR L'ENSEMBLE DU DOSSIER /opt/docker/mediaserver-stack
  file:
    dest: /opt/docker/mediaserver-stack
    owner: "{{ secret.users.me.uid }}"
    group: "{{ secret.users.me.gid }}"
    mode: "0775"
    recurse: true