---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Tableau de bord
startUrl: https://allfabox.fr
language: fr

background:
  image: /images/lucas-k-wQLAGv4_OYs-unsplash.jpg
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 80 # 0-100

useEqualHeights: true
layout:
  Menu:
    tab: Allfabox.fr
    style: row
    columns: 6
  Google:
    tab: Allfabox.fr
    style: row
    columns: 3
  Services:
    tab: Allfabox.fr
    style: row
    columns: 4
  Smarthome:
    tab: Allfabox.fr
    style: row
    columns: 4
  Médias:
    tab: Allfabox.fr
    style: row
    columns: 6 
  Webapps:
    tab: Allfabox.fr
    style: row
    columns: 4
  Monitoring:
    tab: Allfabox.fr
    style: row
    columns: 4
  SIG:
    tab: Allfabox.fr
    style: row
    columns: 4
  Outils:
    tab: SRVIGEO20
    style: row
    columns: 6
  GEO:
    tab: SRVIGEO20
    style: row
    columns: 3
  Intranet:
    tab: SRVIGEO20
    style: row
    columns: 3
  Métiers:
    tab: SRVIGEO20
    style: row
    columns: 2

  Services (localhost):
    tab: LOCALHOST
    columns: 2


showStats: true

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
