---
- name: CHARGEMENT DES VARIABLES PAR DÉFAUT
  include_vars: defaults/main.yml

- name: VÉRIFICATION DE LA PRÉSENCE DE figurine
  stat:
    path: /usr/local/bin/figurine
  register: figurine_binary_exists

- name: DÉFINITION DE LA VARIABLE figurine_is_installed
  set_fact:
    figurine_is_installed: "{{ figurine_binary_exists.stat.exists }}"

- name: VÉRIFICATION DE LA VERSION DE figurine
  shell: "/usr/local/bin/figurine version | awk '{ print $3 }' | cut -c 1-"
  register: figurine_installed_version_registered
  when: figurine_is_installed == True

- name: OBTENTION DE LA DERNIÈRE VERSION
  uri:
    url: https://api.github.com/repos/arsham/figurine/releases/latest
    url_username: "{{ secret.github.api.user | default (omit) }}"
    url_password: "{{ secret.github.api.token | default (omit) }}"
    return_content: true
    force_basic_auth: "{{ secret.github.api.auth | default (omit) }}"
  register: figurine_latest_release
  # when: force_install == True

- name: DÉFINITION DE LA VERSION SI CE N'EST PAS LE CAS
  set_fact:
    figurine_version: "{{ figurine_latest_release.json.tag_name }}"
  # when: figurine_version is undefined and force_install == True

- name: RECUPÉRATION DE L'ARCHITECTURE DU SERVEUR
  vars:
    arch_lut:
      aarch64: arm64
      armv6l: arm
      armv7l: arm
      x86_64: amd64
  set_fact:
    arch: "{{ arch_lut[ansible_architecture] | default(ansible_architecture) }}"

# - name: TÉLÉCHARGEMENT DE LA VERSION SOUHAITÉE
#   get_url:
#     url: "https://github.com/arsham/figurine/releases/download/{{ figurine_version }}/figurine_linux_{{ arch }}_{{ figurine_version }}.tar.gz"
#     dest: /tmp
#   when: force_install == True

- name: TÉLÉCHARGEMENT DE LA VERSION SOUHAITÉE ET EXTRACTION DE L'EXECUTABLE figurine VERS LE RÉPERTOIRE D'INSTALLATION
  unarchive:    
    src: "https://github.com/arsham/figurine/releases/download/{{ figurine_version }}/figurine_linux_{{ arch }}_{{ figurine_version }}.tar.gz"
    dest: /usr/local/bin
    extra_opts: [--strip-components=1]
    remote_src: true
  become: true

- name: CONFIGURATION DU MOTD - MESSAGE OF THE DAY
  template:
    src: figurine.sh.j2
    dest: /etc/profile.d/figurine.sh
  when: figurine_install_login_script
  become: true