---
# grog.package
package_list:
  - name: bash-completion
  - name: ca-certificates
  - name: curl
  - name: duf
  - name: openssh-client
  - name: openssh-server
  - name: sudo
  - name: vim
  - name: wget

docker:
  compose:
    file_mask: "664"
    directory_mask: "775"

portainer:
  agent:
    secret:
      key: "{{ secret.portainer.agent.secret.key }}"

jellystat:
  jwt:
    secret: "{{ secret.jellystat.jwt.secret }}"

homepage:
  proxmox:
    pam: "{{ secret.homepage.proxmox.pam }}"
    token: "{{ secret.homepage.proxmox.token }}"
  pbs:
    pam: "{{ secret.homepage.pbs.pam }}"
    token: "{{ secret.homepage.pbs.token }}"
  portainer:
    token: "{{ secret.homepage.portainer.token }}"
  openweathermap:
    apikey: "{{ secret.homepage.openweathermap.apikey }}"
  pihole:
    apikey: "{{ secret.homepage.pihole.apikey }}"
  unifi:
      user: "{{ secret.homepage.unifi.user }}"
      password: "{{ secret.homepage.unifi.password }}"