- name: VÉRIFICATION DE L'EXISTENCE DU GROUPE UTILISATEUR PRINCIPAL
  group:
    name: "{{ secret.users.me.name }}"
    gid: "{{ secret.users.me.gid }}"
    state: present

- name: AJOUT DE L'UTILISATEUR PRINCIPAL
  ansible.builtin.user:
    name: "{{ secret.users.me.name }}"
    password: "{{ secret.users.me.password | password_hash('sha512') }}"
    uid: "{{ secret.users.me.uid }}"
    group: "{{ secret.users.me.gid }}"
    groups: "{{ secret.users.me.groups }}"
    create_home: "{{ secret.users.me.create_home }}"
    home: "{{ secret.users.me.home }}"
    shell: /bin/bash
    system: "{{ secret.users.me.system }}"
    comment: "{{ secret.users.me.comment }}"

- name: "AJOUT DU FICHIER sudoers POUR L'UTILISATEUR PRINCIPAL"
  template:
    src: sudoer
    dest: "/etc/sudoers.d/{{ secret.users.me.name }}"
    owner: root
    group: root
    mode: 0440

- name: INSTALLATION DES CLÉS SSH POUR L'UTILISATEUR PRINCIPAL
  authorized_key:
    user: "{{ secret.users.me.name }}"
    key: "{{ secret.users.me.ssh.pubkey }}"
    state: present