---
- name: VÉRIFICATION DE L'EXISTENCE DU GROUPE UTILISATEUR jellyfin
  ansible.builtin.group:
    name: "{{ secret.users.jellyfin.group }}"
    gid: "{{ secret.users.jellyfin.gid }}"
    state: present

- name: AJOUT DE L'UTILISATEUR jellyfin
  ansible.builtin.user:
    name: "{{ secret.users.jellyfin.name }}"
    uid: "{{ secret.users.jellyfin.uid }}"
    group: "{{ secret.users.jellyfin.gid }}"
    groups: "{{ secret.users.jellyfin.group }}"
    create_home: "{{ secret.users.jellyfin.create_home }}"
    home: "{{ secret.users.jellyfin.home }}"
    shell: /bin/bash
    system: "{{ secret.users.jellyfin.system }}"
    comment: "{{ secret.users.jellyfin.comment }}"

- name: INSTALLATION DE jellyfin
  include_tasks: installation.yml

- name: CONFIGURATION DE L'ACCÉLÉRATION MATÉRIELLE
  include_tasks: hardware-acceleration.yml