---
- name: CHARGEMENT DES VARIABLES
  include_vars: defaults/main.yml

- name: CRÉATION DU RÉPERTOIRE D'INSTALLATION/CONFIGURATION POUR LA STACK webapps
  become: true
  file:
    path: "/opt/{{ item }}"
    state: directory
    mode: "{{ docker.compose.directory_mask }}"
    owner: "{{ secret.users.me.name }}"
    group: "{{ secret.users.me.gid }}"
  loop:
    - docker
    - docker/webapps-stack

- name: ON S'ASSURE QU'UN FICHIER docker-compose.yml EXISTE
  stat:
    path: /opt/docker/webapps-stack/docker-compose.yml
  register: webapps_stack_docker_compose

- name: SUPPRESSION DE LA STACK webapps SI ELLE EXISTE
  shell:
    chdir: /opt/docker/webapps-stack
    cmd: docker compose down
  when: webapps_stack_docker_compose.stat.exists

- name: INSTALLATION DU FICHIER DE COMPOSITION
  template:
    src: docker-compose.yml.j2
    dest: /opt/docker/webapps-stack/docker-compose.yml
    mode: "{{ docker.compose.file_mask }}"
    owner: "{{ secret.users.me.name }}"
    group: "{{ secret.users.me.gid }}"
    validate: docker compose -f %s config

- name: INSTALLATION DU FICHIER DES VARIABLES D'ENVIRONNEMENT DOCKER
  become: true
  template:
    src: env.j2
    dest: /opt/docker/webapps-stack/.env
    mode: "{{ docker.compose.file_mask }}"
    owner: "{{ secret.users.me.name }}"
    group: "{{ secret.users.me.gid }}"

- name: INSTALLATION/CONFIGURATION DU CONTENEUR filebrowser
  include_tasks: docker/containers/filebrowser.yml

# - name: INSTALLATION/CONFIGURATION DU CONTENEUR homer
#   include_tasks: docker/containers/homer.yml

- name: INSTALLATION/CONFIGURATION DU CONTENEUR homepage
  include_tasks: docker/containers/homepage.yml

- name: INSTALLATION/CONFIGURATION DU CONTENEUR vaultwarden
  include_tasks: docker/containers/vaultwarden.yml

- name: INSTALLATION/CONFIGURATION DU CONTENEUR memos
  include_tasks: docker/containers/memos.yml

- name: INSTALLATION/CONFIGURATION DU CONTENEUR linkace
  include_tasks: docker/containers/linkace.yml

- name: INSTALLATION/CONFIGURATION DU CONTENEUR jellystat
  include_tasks: docker/containers/jellystat.yml

- name: DÉMARRAGE DE LA STACK webapps
  shell:
    chdir: /opt/docker/webapps-stack
    cmd: docker compose up -d

- name: CHANGEMENT DES DROITS UTILISATEUR SUR L'ENSEMBLE DU DOSSIER /opt/docker/webapps-stack
  become: true
  file:
    dest: /opt/docker/webapps-stack
    owner: "{{ secret.users.me.uid }}"
    group: "{{ secret.users.me.gid }}"
    mode: "0777"
    recurse: true