---
- name: CRÉATION DU RÉPERTOIRE D'INSTALLATION POUR tailscale
  file:
    path: /opt/docker/frontend-stack/tailscale
    state: directory
    mode: "{{ docker.compose.directory_mask }}"
    owner: "{{ secret.users.me.name }}"

- name: VÉRIFICATION DE LA PRÉSENCE DE LA CONFIGURATION POUR ACTIVER L'IP FORWARDING
  lineinfile:
    path: /etc/sysctl.conf
    regexp: "^net.ipv4.ip_forward = 1"
    state: absent
  check_mode: yes
  changed_when: false
  register: enable_ip_forwarding

- name: AJOUT DE LA CONFIGURATION POUR ACTIVER L'IP FORWARDING
  lineinfile:
    dest: /etc/sysctl.conf
    insertafter: EOF
    line: |
      # ANSIBLE MANAGED    
      net.ipv4.ip_forward = 1
      net.ipv6.conf.all.forwarding = 1
    unsafe_writes: yes
  when: not enable_ip_forwarding.found

- name: RECHARGEMENT DE LA CONFIGURATION /etc/sysctl.conf
  command: "sysctl -p /etc/sysctl.conf"
