---
# includes tasks file for roles/docker-frontend-stack/traefik
- name: CRÉATION DU RÉPERTOIRE D'INSTALLATION/CONFIGURATION POUR Traefik
  file:
    path: /opt/docker/frontend-stack/traefik
    state: directory
    owner: "{{ secret.users.me.name }}"
    mode: "{{ docker.compose.directory_mask }}"

- name: CRÉATION DU RÉPERTOIRE DU PROVIDER DE FICHIER DE CONFIGURATION POUR Traefik
  file:
    path: /opt/docker/frontend-stack/traefik/extra
    state: directory
    mode: "{{ docker.compose.directory_mask }}"
    owner: "{{ secret.users.me.name }}"

- name: CRÉATION DU RÉPERTOIRE CERTS POUR Traefik
  file:
    path: /opt/docker/frontend-stack/traefik/certs
    state: directory
    mode: "{{ docker.compose.directory_mask }}"
    owner: "{{ secret.users.me.name }}"

- name: CRÉATION DU RÉPERTOIRE DE LOGS POUR Traefik
  file:
    path: /opt/docker/frontend-stack/traefik/logs
    state: directory
    mode: "{{ docker.compose.directory_mask }}"
    owner: "{{ secret.users.me.name }}"

- name: INSTALLATION DU FICHIER DE CONFIGURATION PRINCIPAL DE Traefik
  template:
    src: traefik/traefik.yml.j2
    dest: /opt/docker/frontend-stack/traefik/traefik.yml
    mode: "{{ docker.compose.file_mask }}"
    owner: "{{ secret.users.me.name }}"
    lstrip_blocks: true
    trim_blocks: true

- name: INSTALLATION DU FICHIER DE PROVISION PRINCIPAL
  template:
    src: traefik/extra/main.yml.j2
    dest: /opt/docker/frontend-stack/traefik/extra/main.yml
    mode: "{{ docker.compose.file_mask }}"
    owner: "{{ secret.users.me.name }}"
    