---
docker:
  compose:
    file_mask: "664"
    directory_mask: "775"

portainer:
  agent:
    secret:
      key: "{{ secret.portainer.agent.secret.key }}"

healthchecks:
  secret:
    key: "{{ secret.healthchecks.secret.key }}"