---
- name: start samba service
  service:
    name: smbd
    state: started

- name: restart samba service
  service:
    name: smbd
    state: restarted

- name: reload nfs
  command: "exportfs -ra"