---
- name: MOSQUITTO - INSTALLATION DE LA CONFIGURATION
  copy:
    src: mosquitto/
    dest: /opt/docker/smarthome-stack/mosquitto/
    mode: "{{ docker.compose.directory_mask }}"
    owner: "{{ secret.users.me.uid }}"
    group: "{{ secret.users.me.gid }}"
 
- name: MOSQUITTO - INSTALLATION DU FICHIER DE CONFIGURATION password.conf
  template:
    src: mosquitto/password.conf.j2
    dest: /opt/docker/smarthome-stack/mosquitto/config/password.conf
    mode: "{{ docker.compose.file_mask }}"
    owner: "{{ secret.users.me.name }}"
    group: "{{ secret.users.me.gid }}"