---
- name: MYELECTRICALDATA - CRÉATION DU RÉPERTOIRE D'INSTALLATION/CONFIGURATION
  file:
    path: /opt/docker/smarthome-stack/myelectricaldata
    state: directory
    mode: "{{ docker.compose.directory_mask }}"
    owner: "{{ secret.users.me.uid }}"
    group: "{{ secret.users.me.gid }}"

- name: MYELECTRICALDATA - CRÉATION DU RÉPERTOIRE DE LOG
  file:
    path: /opt/docker/smarthome-stack/myelectricaldata/log
    state: directory
    mode: "{{ docker.compose.directory_mask }}"
    owner: "{{ secret.users.me.uid }}"
    group: "{{ secret.users.me.gid }}"

- name: MYELECTRICALDATA - INSTALLATION DU FICHIER DE CONFIGURATION config.yaml
  template:
    src: myelectricaldata/config.yaml.j2
    dest: /opt/docker/smarthome-stack/myelectricaldata/config.yaml
    mode: "{{ docker.compose.file_mask }}"
    owner: "{{ secret.users.me.name }}"
    group: "{{ secret.users.me.gid }}"