---
- name: ZIGBEE2MQTT - INSTALLATION DE LA CONFIGURATION
  copy:
    src: zigbee2mqtt/
    dest: /opt/docker/smarthome-stack/zigbee2mqtt/
    mode: "{{ docker.compose.directory_mask }}"
    owner: "{{ secret.users.me.uid }}"
    group: "{{ secret.users.me.gid }}"
 
- name: ZIGBEE2MQTT - INSTALLATION DU FICHIER DE CONFIGURATION configuration.yaml
  template:
    src: zigbee2mqtt/configuration.yaml.j2
    dest: /opt/docker/smarthome-stack/zigbee2mqtt/configuration.yaml
    mode: "{{ docker.compose.file_mask }}"
    owner: "{{ secret.users.me.uid }}"
    group: "{{ secret.users.me.gid }}"