---
docker:
  compose:
    file_mask: "664"
    directory_mask: "775"

portainer:
  agent:
    secret:
      key: "{{ secret.portainer.agent.secret.key }}"

jellystat:
  jwt:
    secret: "{{ secret.jellystat.jwt.secret }}"