---
- name: CHARGEMENT DES VARIABLES PAR DÉFAUT
  include_vars: defaults/main.yml

- name: HEALTHCHECKS - CRÉATION DU RÉPERTOIRE D'INSTALLATION/CONFIGURATION
  file:
    path: /opt/docker/monitoring-stack/uptime-kuma
    state: directory
    mode: "{{ docker.compose.directory_mask }}"
    owner: "{{ secret.users.me.uid }}"
    group: "{{ secret.users.me.gid }}"
  
- name: HEALTHCHECKS - CRÉATION DU RÉPERTOIRE D'INSTALLATION/CONFIGURATION
  file:
    path: /opt/docker/monitoring-stack/uptime-kuma/data
    state: directory
    mode: "{{ docker.compose.directory_mask }}"
    owner: "{{ secret.users.me.uid }}"
    group: "{{ secret.users.me.gid }}"
