---
- name: PRÉREQUIS - DÉPENDANCES
  apt:
    name:
      - "python3-pip"
      - "python3-proxmoxer>=1.1.0"
    state: "present"

- name: MISE À JOUR DE Proxmox VE Appliance Manager - pveam
  command: pveam update

- name: TÉLÉCHARGEMENT DES MODÈLES DE CONTENEUR LXC
  command: pveam download iso-nfs {{ item }}
  loop:
    - debian-12-standard_12.2-1_amd64.tar.zst

### Partage de fichier
# - name: CONFIGURATION DU PARTAGE DE FICHIER nfs/samba
#   include_tasks: file-sharing.yml

### Infrastructure
- name: CRÉATION DES CONTENEURS LXC
  include_tasks: infrastructure.yml

### Amorçage des conteneurs (SSH)
- name: AMORÇAGE DES CONTENEURS LXC
  include_tasks: bootstrap.yml