---
- name: CHARGEMENT DES VARIABLES PAR DÉFAUT
  include_vars: defaults/main.yml

- name: FILEBROWSER - CRÉATION DU RÉPERTOIRE D'INSTALLATION/CONFIGURATION
  file:
    path: /opt/docker/webapps-stack/filebrowser
    state: directory
    mode: "{{ docker.compose.directory_mask }}"
    owner: "{{ secret.users.me.uid }}"
    group: "{{ secret.users.me.gid }}"

- name: FILEBROWSER - INSTALLATION DU FICHIER DE CONFIGURATION
  copy:
    src: filebrowser/.filebrowser.json
    dest: /opt/docker/webapps-stack/filebrowser/.filebrowser.json
    mode: "{{ docker.compose.file_mask }}"
    owner: "{{ secret.users.me.uid }}"
    group: "{{ secret.users.me.gid }}"
