---
- name: CHARGEMENT DES VARIABLES PAR DÉFAUT
  include_vars: defaults/main.yml

- name: HOMEPAGE - CRÉATION DU RÉPERTOIRE D'INSTALLATION/CONFIGURATION
  file:
    path: "/opt/docker/webapps-stack/{{ item }}"
    state: directory
    mode: "{{ docker.compose.directory_mask }}"
    owner: "{{ secret.users.me.uid }}"
    group: "{{ secret.users.me.gid }}"
  loop:
    - homepage
    - homepage/config
    - homepage/images
    - homepage/icons

- name: HOMEPAGE - INSTALLATION DES FICHIERS DE CONFIGURATION
  copy:
    src: homepage/config/
    dest: /opt/docker/webapps-stack/homepage/config/
    mode: "{{ docker.compose.directory_mask }}"
    owner: "{{ secret.users.me.uid }}"
    group: "{{ secret.users.me.gid }}"

- name: HOMEPAGE - INSTALLATION DES FICHIERS IMAGES
  copy:
    src: homepage/images/
    dest: /opt/docker/webapps-stack/homepage/images/
    mode: "{{ docker.compose.directory_mask }}"
    owner: "{{ secret.users.me.uid }}"
    group: "{{ secret.users.me.gid }}"

- name: HOMEPAGE - INSTALLATION DES FICHIERS ICONS
  copy:
    src: homepage/icons/
    dest: /opt/docker/webapps-stack/homepage/icons/
    mode: "{{ docker.compose.directory_mask }}"
    owner: "{{ secret.users.me.uid }}"
    group: "{{ secret.users.me.gid }}"
