---
- name: CHARGEMENT DES VARIABLES PAR DÉFAUT
  include_vars: defaults/main.yml

- name: CRÉATION DU RÉPERTOIRE D'INSTALLATION/CONFIGURATION POUR L'ENSEMBLE DES STACKS
  become: true
  file:
    path: "/opt/{{ item }}"
    state: directory
    mode: "{{ docker.compose.directory_mask }}"
    owner: "{{ secret.users.me.name }}"
    group: "{{ secret.users.me.gid }}"
  loop:
    - docker
    - docker/forge-stack
    - docker/forge-stack/forgejo
    - docker/forge-stack/woodpecker
    - docker/forge-stack/woodpecker/server
    - docker/forge-stack/woodpecker/agent

- name: ON S'ASSURE QU'UN FICHIER docker-compose.yml EXISTE
  stat:
    path: /opt/docker/forge-stack/docker-compose.yml
  register: forge_stack_docker_compose

- name: INSTALLATION DU FICHIER DES VARIABLES D'ENVIRONNEMENT DOCKER
  become: true
  template:
    src: env.j2
    dest: /opt/docker/forge-stack/.env
    mode: "{{ docker.compose.file_mask }}"
    owner: "{{ secret.users.me.name }}"
    group: "{{ secret.users.me.gid }}"

- name: SUPPRESSION DE LA STACK forge SI ELLE EXISTE
  shell:
    chdir: /opt/docker/forge-stack
    cmd: docker compose down
  when: forge_stack_docker_compose.stat.exists

- name: INSTALLATION DU FICHIER DE COMPOSITION
  template:
    src: docker-compose.yml.j2
    dest: /opt/docker/forge-stack/docker-compose.yml
    mode: "{{ docker.compose.file_mask }}"
    owner: "{{ secret.users.me.name }}"
    group: "{{ secret.users.me.gid }}"
    validate: docker compose -f %s config

- name: DÉMARRAGE DE LA STACK forge
  shell:
    chdir: /opt/docker/forge-stack
    cmd: docker compose up -d --remove-orphans

# - name: PRÉREQUIS POUR L'ÉXECUTION DU MODULE docker ANSIBLE
#   dnf:
#     name: python3-requests
#     state: present
#   become: true

- name: CHANGEMENT DES DROITS UTILISATEUR SUR L'ENSEMBLE DU DOSSIER /opt/docker/forge-stack
  become: true
  file:
    dest: /opt/docker/forge-stack
    owner: "{{ secret.users.me.uid }}"
    group: "{{ secret.users.me.gid }}"
    mode: "0755"
    recurse: true