---
- name: ARRÊT DE TOUS LES CONTENEURS LXC DE L'INFRASTRUCTURE
  ansible.builtin.command: "pct shutdown {{ item.lxc }}"
  ignore_errors: true
  loop:
    - {"lxc":"110"}
    - {"lxc":"120"}
    - {"lxc":"130"}
    - {"lxc":"140"}
    - {"lxc":"141"}
    - {"lxc":"142"}
    - {"lxc":"143"}
    - {"lxc":"150"}
    - {"lxc":"160"}
    - {"lxc":"170"}

- name: SUPPRESSION DE TOUS LES CONTENEURS LXC DE L'INFRASTRUCTURE
  ansible.builtin.command: "pct destroy {{ item.lxc }}"
  ignore_errors: true
  loop:
    - {"lxc":"110"}
    - {"lxc":"120"}
    - {"lxc":"130"}
    - {"lxc":"140"}
    - {"lxc":"141"}
    - {"lxc":"142"}
    - {"lxc":"143"}
    - {"lxc":"150"}
    - {"lxc":"160"}
    - {"lxc":"170"}