---
- name: LNXLINK - INSTALLATION DE pipx ET AUTRES PRÉREQUIS LOGICIELS
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - pipx
    - libdbus-1-3
    - libdbus-1-dev
    - libcairo2-dev
    - libgirepository1.0-dev
    - libdbus-glib-1-dev
    - libglib2.0-dev
    #- patchelf
    #- meson
    #- python3-pip
    #- python3-dbus

- name: LNXLINK - INSTALLATION
  command: pipx install lnxlink

- name: LNXLINK - COPIE DU BINAIRE DANS /usr/local/bin
  copy:
    src: /root/.local/bin/lnxlink
    dest: /usr/local/bin
    mode: +x
    remote_src: true

- name: LNXLINK - CRÉATION DU RÉPERTOIRE STOCKANT LA CONFIGURATION
  file:
    path: "{{ secret.users.me.home }}/.lnxlink"
    state: directory
    owner: "{{ secret.users.me.uid }}"
    group: "{{ secret.users.me.gid }}"

- name: LNXLINK - INSTALLATION DU FICHIER DE CONFIGURATION
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"    
  loop:
    - {src: "config.yaml.j2", dest: "{{ secret.users.me.home }}/.lnxlink/config.yaml", mode: "0644", owner: "{{ secret.users.me.uid }}", group: "{{ secret.users.me.gid }}"}

- name: LNXLINK - INSTALLATION DU FICHIER DE SERVICE systemd
  template:
    src: lnxlink.service.j2
    dest: /etc/systemd/system/lnxlink.service
    owner: root
    group: root
    mode: 0644

- name: LNXLINK - CHARGEMENT DU SERVICE lnxlink.service
  systemd:
    enabled: true
    daemon-reload: true
    state: started
    name: lnxlink.service
    no_block: true