---
- name: CHARGEMENT DES VARIABLES PAR DÉFAUT
  include_vars: defaults/main.yml

- name: HEALTHCHECKS - CRÉATION DU RÉPERTOIRE D'INSTALLATION/CONFIGURATION
  file:
    path: "/opt/docker/sysadmin-stack/{{ item }}"
    state: directory
    mode: "{{ docker.compose.directory_mask }}"
    owner: "{{ secret.users.me.uid }}"
    group: "{{ secret.users.me.gid }}"
  loop:
    - healthchecks
    - healthchecks/config

- name: HEALTHCHECKS - INSTALLATION DU FICHIER DE BDD
  copy:
    src: healthchecks/hc.sqlite
    dest: /opt/docker/sysadmin-stack/healthchecks/config/hc.sqlite
    mode: "{{ docker.compose.file_mask }}"
    owner: "{{ secret.users.me.uid }}"
    group: "{{ secret.users.me.gid }}"